CONTRIBUTING.md, README.md
=> chore(github): added contributing.md

packages/docs/.vitepress/config.ts, packages/docs/.vitepress/theme/custom.css, packages/docs/.vitepress/theme/icons.ts
=> docs: Normalize doc theme to match app design

.github/workflows/cd-app-prod.yaml, .github/workflows/cd-preview-build.yaml, .github/workflows/cd-preview-deploy.yaml
=> chore(cd): preview app for forks PRs

packages/app-client/src/locales/en.json, packages/app-client/src/locales/es.json, packages/app-client/src/locales/fr.json, packages/app-client/src/modules/notes/pages/create-note.page.tsx
=> feat(creation): added spinner when creating big notes

packages/app-server/src/index.node.ts
=> fix(config): log when invalid config

packages/app-client/src/locales/de.json, packages/app-client/src/modules/i18n/i18n.provider.tsx
...like in the last commit metioned, because of alphabetical order. Sorry for the inconvenience.
=> feat(lang): add German language

packages/app-client/src/modules/notes/pages/view-note.page.tsx
Preserve line breaks + overflow x scroll
Closes #228
=> fix(note-viewer): preserve line breaks

packages/app-client/package.json, packages/app-server/package.json, packages/cli/package.json, packages/crypto/package.json, packages/docs/package.json, packages/lib/package.json, pnpm-lock.yaml, pnpm-workspace.yaml
=> chore(deps): more deps in pnpm catalog

packages/app-client/src/modules/config/config.constants.ts, packages/app-client/src/modules/config/config.types.ts, packages/app-client/src/modules/notes/pages/create-note.page.tsx, packages/app-server/src/modules/app/config/config.ts
=> feat(config): configure the default delete-after-reading button state

packages/app-client/package.json, packages/app-client/src/index.tsx, packages/app-client/src/locales/en.json, packages/app-client/src/locales/fr.json, packages/app-client/src/modules/notes/pages/create-note.page.tsx, packages/app-client/src/modules/shared/files/convert.ts, packages/app-client/src/modules/shared/files/download.ts, packages/app-client/src/modules/ui/components/sonner.tsx, pnpm-lock.yaml
Added QR-Code sharing on note creation 
Closes #274
=> feat(sharing): added qr code when note is created

packages/app-client/src/locales/it.json, packages/app-client/src/modules/i18n/i18n.constants.ts
=> Added Italian language

packages/docs/src/self-hosting/other-platforms.md
=> docs(other-platforms): Add UmbrelOS app store link

.github/workflows/cd-docker-release.yaml, Dockerfile, Dockerfile.rootless
=> feat(docker): armv7 support

packages/app-client/src/locales/en.json, packages/app-client/src/locales/fr.json, packages/app-client/src/modules/notes/pages/view-note.page.tsx
=> feat(note-view): added loading state

packages/lib/src/notes/notes.models.test.ts
=> chore: update notes.models.test.ts

packages/app-client/src/locales/locales.ts, packages/app-client/src/locales/zh-TW.json
Hello, I've added Traditional Chinese (zh-TW) language.
=> Add Chinese (zh-TW) translations

packages/app-client/src/locales/pl.json
Adding Polish language support
=> Add Polish Language support

packages/app-server/src/index.node.ts, packages/app-server/src/modules/app/config/config.ts, packages/docs/src/self-hosting/configuration.md
=> feat(node): add support for native HTTPS configuration

packages/app-client/src/modules/ui/layouts/app.layout.tsx
=> feat(ui): conditionally display "New Note" button based on authentication status

packages/docs/src/self-hosting/configuration.md, packages/docs/src/self-hosting/docker.md
=> fix(docs): corrected ghcr Docker image references in self-hosting documentation
